{
var key
key=argument0;

switch(key)
{
case 0: return string(key); break;
case 1: return string(key); break;
case 2: return string(key); break;
case 3: return string(key); break;
case 4: return string(key); break;
case 5: return string(key); break;
case 6: return string(key); break;
case 7: return string(key); break;
case 8: return"Backspace"; break;
case 9: return"Tab"; break;
case 10: return string(key); break;
case 11: return string(key); break;
case 12: return"Numpad 5 (nmlk off)"; break;
case 13: return"Enter"; break;
case 14: return string(key); break;
case 15: return string(key); break;
case 16: return string(key); break;
case 17: return string(key); break;
case 18: return string(key); break;
case 19: return"Pause"; break;
case 20: return"Caps lock"; break;
case 21: return string(key); break;
case 22: return string(key); break;
case 23: return string(key); break;
case 24: return string(key); break;
case 25: return string(key); break;
case 26: return string(key); break;
case 27: return"Escape"; break;
case 28: return string(key); break;
case 29: return string(key); break;
case 30: return string(key); break;
case 31: return string(key); break;
case 32: return"Space"; break;
case 33: return"Page up"; break;
case 34: return"Page down"; break;
case 35: return"End"; break;
case 36: return"Home"; break;
case 37: return"Left"; break;
case 38: return"Up"; break;
case 39: return"Right"; break;
case 40: return"Down"; break;
case 41: return string(key); break;
case 42: return string(key); break;
case 43: return string(key); break;
case 44: return string(key); break;
case 45: return"Insert"; break;
case 46: return"Delete"; break;
case 47: return string(key); break;
case 48: return"0"; break;
case 49: return"1"; break;
case 50: return"2"; break;
case 51: return"3"; break;
case 52: return"4"; break;
case 53: return"5"; break;
case 54: return"6"; break;
case 55: return"7"; break;
case 56: return"8"; break;
case 57: return"9"; break;
case 58: return string(key); break;
case 59: return string(key); break;
case 60: return string(key); break;
case 61: return string(key); break;
case 62: return string(key); break;
case 63: return string(key); break;
case 64: return string(key); break;
case 65: return"A"; break;
case 66: return"B"; break;
case 67: return"C"; break;
case 68: return"D"; break;
case 69: return"E"; break;
case 70: return"F"; break;
case 71: return"G"; break;
case 72: return"H"; break;
case 73: return"I"; break;
case 74: return"J"; break;
case 75: return"K"; break;
case 76: return"L"; break;
case 77: return"M"; break;
case 78: return"N"; break;
case 79: return"O"; break;
case 80: return"P"; break;
case 81: return"Q"; break;
case 82: return"R"; break;
case 83: return"S"; break;
case 84: return"T"; break;
case 85: return"U"; break;
case 86: return"V"; break;
case 87: return"W"; break;
case 88: return"X"; break;
case 89: return"Y"; break;
case 90: return"Z"; break;
case 91: return"Windows"; break;
case 92: return string(key); break;
case 93: return string(key); break;
case 94: return string(key); break;
case 95: return string(key); break;
case 96: return"Numpad 0"; break;
case 97: return"Numpad 1"; break;
case 98: return"Numpad 2"; break;
case 99: return"Numpad 3"; break;
case 100: return"Numpad 4"; break;
case 101: return"Numpad 5"; break;
case 102: return"Numpad 6"; break;
case 103: return"Numpad 7"; break;
case 104: return"Numpad 8"; break;
case 105: return"Numpad 9"; break;
case 106: return"Numpad *"; break;
case 107: return"Numpad +"; break;
case 109: return"Numpad -"; break;
case 110: return"Numpad ."; break;
case 111: return"Numpad /"; break;
case 112: return"F1"; break;
case 113: return"F2"; break;
case 114: return"F3"; break;
case 115: return"F4"; break;
case 116: return"F5"; break;
case 117: return"F6"; break;
case 118: return"F7"; break;
case 119: return"F8"; break;
case 120: return"F9"; break;
case 121: return"F10"; break;
case 122: return"F11"; break;
case 123: return"F12"; break;
case 124: return string(key); break;
case 125: return string(key); break;
case 126: return string(key); break;
case 127: return string(key); break;
case 128: return string(key); break;
case 129: return string(key); break;
case 130: return string(key); break;
case 131: return string(key); break;
case 132: return string(key); break;
case 133: return string(key); break;
case 134: return string(key); break;
case 135: return string(key); break;
case 136: return string(key); break;
case 137: return string(key); break;
case 138: return string(key); break;
case 139: return string(key); break;
case 140: return string(key); break;
case 141: return string(key); break;
case 142: return string(key); break;
case 143: return string(key); break;
case 144: return"Num lock"; break;
case 145: return"Scroll lock"; break;
case 146: return string(key); break;
case 147: return string(key); break;
case 148: return string(key); break;
case 149: return string(key); break;
case 150: return string(key); break;
case 151: return string(key); break;
case 152: return string(key); break;
case 153: return string(key); break;
case 154: return string(key); break;
case 155: return string(key); break;
case 156: return string(key); break;
case 157: return string(key); break;
case 158: return string(key); break;
case 159: return string(key); break;
case 160: return"Shift (left)"; break;
case 161: return"Shift (right)"; break;
case 162: return"Ctrl (left)"; break;
case 163: return"Ctrl (right)"; break;
case 164: return"Alt (left)"; break;
case 165: return"Alt (right)"; break;
case 166: return string(key); break;
case 167: return string(key); break;
case 168: return string(key); break;
case 169: return string(key); break;
case 170: return string(key); break;
case 171: return string(key); break;
case 172: return string(key); break;
case 173: return string(key); break;
case 174: return string(key); break;
case 175: return string(key); break;
case 176: return string(key); break;
case 177: return string(key); break;
case 178: return string(key); break;
case 179: return string(key); break;
case 180: return string(key); break;
case 181: return string(key); break;
case 182: return string(key); break;
case 183: return string(key); break;
case 184: return string(key); break;
case 185: return string(key); break;
case 186: return";"; break;
case 187: return"="; break;
case 188: return","; break;
case 189: return"-"; break;
case 190: return"."; break;
case 191: return"?"; break;
case 192: return"~"; break;
case 193: return string(key); break;
case 194: return string(key); break;
case 195: return string(key); break;
case 196: return string(key); break;
case 197: return string(key); break;
case 198: return string(key); break;
case 199: return string(key); break;
case 200: return string(key); break;
case 201: return string(key); break;
case 202: return string(key); break;
case 203: return string(key); break;
case 204: return string(key); break;
case 205: return string(key); break;
case 206: return string(key); break;
case 207: return string(key); break;
case 208: return string(key); break;
case 209: return string(key); break;
case 210: return string(key); break;
case 211: return string(key); break;
case 212: return string(key); break;
case 213: return string(key); break;
case 214: return string(key); break;
case 215: return string(key); break;
case 216: return string(key); break;
case 217: return string(key); break;
case 218: return string(key); break;
case 219: return"["; break;
case 220: return"\"; break;
case 221: return"]"; break;
case 222: return"'"; break;
}
}
